default:
  tags:
    - docker
  image: registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:latest

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - checks
  - test
  - integration

.python-job:
  before_script:
    - scl enable rh-python38 -- python --version
    - scl enable rh-python38 -- python -m pip install --user -r requirements-dev.txt

ruff:
  extends: .python-job
  stage: checks
  script:
    - scl enable rh-python38 -- python -m ruff check tests just_bin_it

ruff-format:
  extends: .python-job
  stage: checks
  script:
    - scl enable rh-python38 -- python -m ruff format --check tests just_bin_it

isort:
  extends: .python-job
  stage: checks
  script:
    - scl enable rh-python38 -- python -m isort --check-only .

unit-tests:
  extends: .python-job
  stage: test
  script:
    - scl enable rh-python38 -- pyenv global 3.8 3.9 3.10
    - scl enable rh-python38 -- pyenv versions
    - export PATH="/home/jenkins/.pyenv/shims:$PATH"
    - scl enable rh-python38 -- python -m nox -- --junitxml=test-output.xml
  artifacts:
    paths:
      - test-output.xml
    reports:
      junit: test-output.xml

integration-tests:
  stage: integration
  image: docker:28
  resource_group: just-bin-it-integration-tests
  script:
    - docker info
    - docker compose -f integration-tests/docker-compose.yml -p kafka down --volumes --remove-orphans || true
    - >
      docker run --rm
      --network host
      -v /var/run/docker.sock:/var/run/docker.sock
      -v "$CI_PROJECT_DIR":"$CI_PROJECT_DIR"
      -w "$CI_PROJECT_DIR"
      registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-build-node:latest
      bash -lc '
      scl enable rh-python38 -- python -m venv test_env &&
      source test_env/bin/activate &&
      python -m pip install --upgrade pip &&
      python -m pip install -r requirements-dev.txt &&
      python -m pip install -r integration-tests/requirements.txt &&
      python -m pip install "requests<2.30.0" &&
      cd integration-tests &&
      python -m pytest -s --junitxml=./IntegrationTestsOutput.xml .
      '
  after_script:
    - docker compose -f integration-tests/docker-compose.yml -p kafka down --volumes --remove-orphans || true
    - rm -rf test_env
    - rm -rf integration-tests/output-files/* || true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  timeout: 30m
  artifacts:
    when: always
    paths:
      - integration-tests/IntegrationTestsOutput.xml
    reports:
      junit: integration-tests/IntegrationTestsOutput.xml
