[project]
name = "just-bin-it"
version = "0.1.0"
description = "A lightweight program for histogramming neutron event data"
readme = "README.md"
license = { text = "BSD-2-Clause" }
requires-python = ">=3.12"
dependencies = [
    "ConfigArgParse>=1.7.5,<2",
    "confluent-kafka==2.4.0",
    "ess-streaming-data-types>=0.27,<0.28",
    "fast-histogram>=0.14,<0.15",
    "graphyte>=1.7.1,<2",
    "numpy>=2,<3",
]

[project.optional-dependencies]
gui = [
    "matplotlib>=3.10,<4",
    "PyQt6>=6.10,<7",
]

[dependency-groups]
dev = [
    "isort==5.13.2",
    "mock>=5.2.0",
    "nox>=2025.11.12",
    "pre-commit>=4.5.0",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff==0.4.4",
]
integration = [
    "pytest>=9.0.2",
    "pytest-rerunfailures>=16.1",
]

[project.scripts]
just-bin-it = "just_bin_it.cli:main"
jbi-generate-event-data = "just_bin_it.generate_event_data:cli"
jbi-view-output-messages = "just_bin_it.view_output_messages:cli"
jbi-viewer = "just_bin_it.viewer:cli"

[build-system]
requires = ["uv_build>=0.10.12,<0.11.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "ecdc-pypi"
url = "https://artifactory.esss.lu.se/artifactory/api/pypi/ecdc-pypi/simple"
publish-url = "https://artifactory.esss.lu.se/artifactory/api/pypi/ecdc-pypi"
default = true

[tool.uv.build-backend]
module-root = ""
